### ISSUE TITLE
Vue component inside GSTC slot

### ISSUE THREAD

**Issue by skix123** [neuronetio/vue-gantt-schedule-timeline-calendar-example#2]
Hi, is it possible to use Vue component inside GSTC slot or lithtml is the only option?

I remember it was possible in old `gantt-elastic` project to import custom component to override the default one, is it doable now?

**Comment by neuronetio** [comment]
Only `lithtml` template because current version is not created in vue anymore.

**Comment by neuronetio** [comment]
To work around this, you can try to create a web-component from a vue component and then put it in the `lithtml` template or string, but this takes extra steps.

**Comment by skix123** [comment]
I see, thank you for instant reply!
